export default [
    {
        img: "/CardImages/card1.png",
        title: "Clevertap",
        text: "CleverTap is a user engagement and retention platform used by Premier League, Bolt, Gojek, Vodafone, Sony and over 10000 other mobile apps globally. Accel portcos get access to the CleverTap for Startups edition at a substantially discounted rate. Please refer to this link for more details.",
        img1: "/img.png",
        link:"https://clevertap.com/",
    },
    {
        img: "/CardImages/card2.png",
        title: "Chargebee",
        text: "Get access to Chargebee credits",
        img1: "/img.png",
        link:"https://www.chargebee.com/",
    },
    {
        img: "/CardImages/card3.png",
        title: "Segment",
        text: "Get access to the Segment startup plan",
        img1: "/img.png",
        link:"https://segment.com/",
    },
    {
        img: "/CardImages/card4.png",
        title: "Freshworks",
        text: "Get access to Freshwork's suite of products",
        img1: "/img.png",
        link:"https://www.freshworks.com/",
    },
    {
        img: "/CardImages/card5.png",
        title: "AWS",
        text: "Get access to premium AWS support for your teams",
        img1: "/img.png",
        link:"https://aws.amazon.com/",
    },
    {
        img: "/CardImages/card6.png",
        title: "SaaSBooMi",
        text: "A community of SaaS Founders and product builders who came together to learn from each other’s journeys across different life stages of their companies-from ARR of $0 to $100 million and beyond.",
        img1: "/img.png",
        link:"https://saasboomi.com/",
    },
    {
        img: "/CardImages/card7.png",
        title: "Product Growth",
        text: "Product Growth is a collaborative hub created to facilitate the creation and exchange of high-value knowledge through various media",
        img1: "/img.png",
        link:"https://www.productgrowth.org/",
    },
    {
        img: "/CardImages/card8.png",
        title: "LetsVenture",
        text: "LetsVenture enables startups looking to raise seed / angel money to create investment ready profiles online, and connect to accredited Investors.",
        img1: "/img.png",
        link:"https://www.letsventure.com/",
    },
    {
        img: "/CardImages/card9.png",
        title: "C",
        text: "Pi Ventures finds, funds and supports the best teams who are using Artificial Intelligence, Machine Learning and Internet of Things to solve real world problems for next 6bn.",
        img1: "/img.png",
        link:"https://www.piventures.in/",
    },
    {
        img: "/CardImages/card10.png",
        title: "Upekkha",
        text: "Upekkha is an Accelerator that helps founders build Value SaaS business where business grows fast in the most capital-efficient way.",
        img1: "/img.png",
        link:"https://www.upekkha.io/",
    },
    {
        img: "/CardImages/card11.png",
        title: "BITS Conquest",
        text: "Conquest, an initiative by the Center for Entrepreneurial Leadership, BITS Pilani, is India's First Student-Run Startup Accelerator",
        img1: "/img.png",
        link:"https://www.conquest.org.in/",
    },
    {
        img: "/CardImages/card12.png",
        title: "Microsoft",
        text: "Microsoft develops, manufactures, licenses, supports, and sells computer software, consumer electronics, personal computers, and related services.",
        img1: "/img.png",
        link:"https://www.microsoft.com/en-in",
    },
    {
        img: "/CardImages/card13.png",
        title: "Nasscom",
        text: "NASSCOM helps IT BPM industries in creating a conducive business environment, simplifying policies, promoting intellectual capital and strengthening the talent",
        img1: "/img.png",
        link:"https://nasscom.in/",
    },
    {
        img: "/CardImages/card14.png",
        title: "#PayItForward",
        text: "Community initiative to help under-represented founders in the startup ecosystem",
        img1: "/img.png",
        link:"https://www.notion.so/PayItForward-Applicant-Home-dee9de48c78043c7a5b42be2e4a2026f",
    },
    {
        img: "/CardImages/card15.png",
        title: "Miro",
        text: "We believe that Miro can help startup teams collaborate faster and more clearly, inspire new ideas during interactive meetings, and design products that keep user research front and center.",
        img1: "/img.png",
        link:"https://miro.com/",
    },
]